/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author me
 */
public class frame extends javax.swing.JFrame {
    private static String operation ="";
    private static double n1 =0;
    private static double n2 =0;
    private static double result;

    /**
     * Creates new form frame
     */
    public frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtval = new javax.swing.JTextField();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        mul = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        division = new javax.swing.JButton();
        lcl = new javax.swing.JLabel();
        dot = new javax.swing.JButton();
        cll = new javax.swing.JButton();
        ba = new javax.swing.JButton();
        sqt = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        mul.setText("*");
        mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulActionPerformed(evt);
            }
        });

        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        division.setText("/");
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });

        lcl.setText("<html>\n<b>\nCalculator\n</b>\n</html>");

        dot.setText(".");
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });

        cll.setText("clear");
        cll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cllActionPerformed(evt);
            }
        });

        ba.setText("back");
        ba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baActionPerformed(evt);
            }
        });

        sqt.setText("sqrt");
        sqt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(73, 73, 73)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtval, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(b7)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(b8)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(b9))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(9, 9, 9)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(b2)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(b3))
                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                        .addComponent(b0)
                                                                                                        .addGap(18, 18, 18)
                                                                                                        .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                                        .addComponent(b4)
                                                                                                        .addGap(18, 18, 18)
                                                                                                        .addComponent(b5)
                                                                                                        .addGap(18, 18, 18)
                                                                                                        .addComponent(b6))))))
                                                                .addGap(54, 54, 54)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(division)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(sqt))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(plus)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(dot))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(mul)
                                                                                        .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(cll)
                                                                                        .addComponent(ba)))))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(171, 171, 171)
                                                .addComponent(lcl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lcl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(txtval, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(plus)
                                                        .addComponent(dot))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(mul)
                                                        .addComponent(cll, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ba))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(sqt))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(b3)
                                                        .addComponent(b2)
                                                        .addComponent(b1))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(b4)
                                                        .addComponent(b5)
                                                        .addComponent(b6))
                                                .addGap(14, 14, 14)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(b8)
                                                        .addComponent(b9)
                                                        .addComponent(b7))
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(b0)
                                                        .addComponent(equal)
                                                        .addComponent(division))))
                                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String str =txtval.getText()+ b7.getText();
        txtval.setText(str);
    }

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String str =txtval.getText()+ b1.getText();
        txtval.setText(str);
    }

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String str =txtval.getText()+ b2.getText();
        txtval.setText(str);
    }

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String str =txtval.getText()+ b3.getText();
        txtval.setText(str);
    }

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String str =txtval.getText()+ b4.getText();
        txtval.setText(str);
    }

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String str =txtval.getText()+ b5.getText();
        txtval.setText(str);
    }

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String str = txtval.getText()+b6.getText();
        txtval.setText(str);
    }

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String str =txtval.getText()+ b8.getText();
        txtval.setText(str);
    }

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String str = txtval.getText()+b9.getText();
        txtval.setText(str);
    }

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String str = txtval.getText()+b0.getText();
        txtval.setText(str);
    }

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        n2 = Double.valueOf(txtval.getText());
        if(operation== "+"){
            result = (double)(n1+n2);
        }
        else if(operation== "-"){
            result = (double)(n1-n2);
        }
        else if(operation== "*"){
            result = (double)(n1*n2);
        }
        else if(operation== "/"){
            result = (double)(n1/n2);
        }
        txtval.setText(String.valueOf(result));
    }

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        operation = "+";
        n1 = Double.valueOf(txtval.getText());
        txtval.setText("");

    }

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        operation = "-";
        n1 = Double.valueOf(txtval.getText());
        txtval.setText("");

    }

    private void mulActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        operation = "*";
        n1 = Double.valueOf(txtval.getText());
        txtval.setText("");
    }

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        operation = "/";
        n1 = Double.valueOf(txtval.getText());
        txtval.setText("");
    }

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String str =txtval.getText()+ dot.getText();
        txtval.setText(str);
    }

    private void cllActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        txtval.setText("");
    }

    private void baActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String s = txtval.getText();
        s = s.substring(0,s.length()-1);
        txtval.setText(s);
    }

    private void sqtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        n1 = Double.valueOf(txtval.getText());
        double sqr = Math.sqrt(n1);
        txtval.setText(String.valueOf(sqr));
    }


    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
                                            public void run() {
                                                new frame().setVisible(true);
                                            }
                                        }
        );

    }

    // Variables declaration - do not modify
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton ba;
    private javax.swing.JButton cll;
    private javax.swing.JButton division;
    private javax.swing.JButton dot;
    private javax.swing.JButton equal;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lcl;
    private javax.swing.JButton minus;
    private javax.swing.JButton mul;
    private javax.swing.JButton plus;
    private javax.swing.JButton sqt;
    private javax.swing.JTextField txtval;
    // End of variables declaration
}
